# Generated by Django 5.1.2 on 2025-09-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_interval_days', models.IntegerField()),
                ('base_water_litre', models.FloatField()),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
